//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItemOption
    {
        public long ID { get; set; }
        public Nullable<long> CartItemID { get; set; }
        public Nullable<long> OptionsID { get; set; }
    }
}
