//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EcommerceEntities : DbContext
    {
        public EcommerceEntities()
            : base("name=EcommerceEntities")
        {
            this.Configuration.LazyLoadingEnabled = this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cart> Carts { get; set; }
        public DbSet<CartItem> CartItems { get; set; }
        public DbSet<OrderStatu> OrderStatus { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Tax> Taxes { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CartItemOption> CartItemOptions { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductAttribute> ProductAttributes { get; set; }
        public DbSet<Product_Attribute> Product_Attribute { get; set; }
        public DbSet<ProductAttributeOption> ProductAttributeOptions { get; set; }
        public DbSet<ProductCateogory> ProductCateogories { get; set; }
        public DbSet<ProductSubCategory> ProductSubCategories { get; set; }
    
        public virtual ObjectResult<GetProduct_Result> GetProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProduct_Result>("GetProduct");
        }
    
        public virtual ObjectResult<GetProductByCategory_Result> GetProductByCategory(Nullable<int> categoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductByCategory_Result>("GetProductByCategory", categoryIdParameter);
        }
    
        public virtual ObjectResult<GetOrderStatusList_Result> GetOrderStatusList(Nullable<int> pageIndex, Nullable<int> pageSize, string filter, string sortOrder, string sortColoumn)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("pageIndex", pageIndex) :
                new ObjectParameter("pageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var filterParameter = filter != null ?
                new ObjectParameter("filter", filter) :
                new ObjectParameter("filter", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(string));
    
            var sortColoumnParameter = sortColoumn != null ?
                new ObjectParameter("sortColoumn", sortColoumn) :
                new ObjectParameter("sortColoumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderStatusList_Result>("GetOrderStatusList", pageIndexParameter, pageSizeParameter, filterParameter, sortOrderParameter, sortColoumnParameter);
        }
    
        public virtual ObjectResult<GetCartItemsByCartId_Result> GetCartItemsByCartId(Nullable<int> cartId)
        {
            var cartIdParameter = cartId.HasValue ?
                new ObjectParameter("cartId", cartId) :
                new ObjectParameter("cartId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCartItemsByCartId_Result>("GetCartItemsByCartId", cartIdParameter);
        }
    
        public virtual ObjectResult<GetOrderByCustomerId_Result> GetOrderByCustomerId(Nullable<int> custmerId)
        {
            var custmerIdParameter = custmerId.HasValue ?
                new ObjectParameter("custmerId", custmerId) :
                new ObjectParameter("custmerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderByCustomerId_Result>("GetOrderByCustomerId", custmerIdParameter);
        }
    
        public virtual ObjectResult<GetCustomerById_Result> GetCustomerById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerById_Result>("GetCustomerById", idParameter);
        }
    
        public virtual ObjectResult<ValidateUser_Result> ValidateUser(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidateUser_Result>("ValidateUser", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<GetOrders_Result> GetOrders(Nullable<int> pageIndex, Nullable<int> pageSize, string filter, string sortOrder, string sortColoumn)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("pageIndex", pageIndex) :
                new ObjectParameter("pageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var filterParameter = filter != null ?
                new ObjectParameter("filter", filter) :
                new ObjectParameter("filter", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(string));
    
            var sortColoumnParameter = sortColoumn != null ?
                new ObjectParameter("sortColoumn", sortColoumn) :
                new ObjectParameter("sortColoumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrders_Result>("GetOrders", pageIndexParameter, pageSizeParameter, filterParameter, sortOrderParameter, sortColoumnParameter);
        }
    
        public virtual ObjectResult<GetCategoryList_Result> GetCategoryList(Nullable<int> pageIndex, Nullable<int> pageSize, string filter, string sortOrder, string sortColoumn)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("pageIndex", pageIndex) :
                new ObjectParameter("pageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var filterParameter = filter != null ?
                new ObjectParameter("filter", filter) :
                new ObjectParameter("filter", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(string));
    
            var sortColoumnParameter = sortColoumn != null ?
                new ObjectParameter("sortColoumn", sortColoumn) :
                new ObjectParameter("sortColoumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategoryList_Result>("GetCategoryList", pageIndexParameter, pageSizeParameter, filterParameter, sortOrderParameter, sortColoumnParameter);
        }
    
        public virtual ObjectResult<GetProductById_Result> GetProductById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductById_Result>("GetProductById", idParameter);
        }
    
        public virtual ObjectResult<GetProductList_Result> GetProductList(Nullable<int> pageIndex, Nullable<int> pageSize, string filter, string sortOrder, string sortColoumn)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("pageIndex", pageIndex) :
                new ObjectParameter("pageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var filterParameter = filter != null ?
                new ObjectParameter("filter", filter) :
                new ObjectParameter("filter", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(string));
    
            var sortColoumnParameter = sortColoumn != null ?
                new ObjectParameter("sortColoumn", sortColoumn) :
                new ObjectParameter("sortColoumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductList_Result>("GetProductList", pageIndexParameter, pageSizeParameter, filterParameter, sortOrderParameter, sortColoumnParameter);
        }
    
        public virtual ObjectResult<GetSubCategoryList_Result> GetSubCategoryList(Nullable<int> pageIndex, Nullable<int> pageSize, string filter, string sortOrder, string sortColoumn)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("pageIndex", pageIndex) :
                new ObjectParameter("pageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var filterParameter = filter != null ?
                new ObjectParameter("filter", filter) :
                new ObjectParameter("filter", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(string));
    
            var sortColoumnParameter = sortColoumn != null ?
                new ObjectParameter("sortColoumn", sortColoumn) :
                new ObjectParameter("sortColoumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubCategoryList_Result>("GetSubCategoryList", pageIndexParameter, pageSizeParameter, filterParameter, sortOrderParameter, sortColoumnParameter);
        }
    
        public virtual ObjectResult<GetAttributeList_Result> GetAttributeList(Nullable<int> pageIndex, Nullable<int> pageSize, string filter, string sortOrder, string sortColoumn)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("pageIndex", pageIndex) :
                new ObjectParameter("pageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var filterParameter = filter != null ?
                new ObjectParameter("filter", filter) :
                new ObjectParameter("filter", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(string));
    
            var sortColoumnParameter = sortColoumn != null ?
                new ObjectParameter("sortColoumn", sortColoumn) :
                new ObjectParameter("sortColoumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAttributeList_Result>("GetAttributeList", pageIndexParameter, pageSizeParameter, filterParameter, sortOrderParameter, sortColoumnParameter);
        }
    
        public virtual ObjectResult<GetProductWiseOrders_Result> GetProductWiseOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductWiseOrders_Result>("GetProductWiseOrders");
        }
    }
}
