//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<int> GrandTotal { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> OrderStatusID { get; set; }
    
        public virtual Order Order1 { get; set; }
        public virtual Order Order2 { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
