//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> ProductCateogoryID { get; set; }
        public string Image { get; set; }
        public Nullable<int> Quentity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<long> ProductSubCategoryID { get; set; }
    
        public virtual Product Product1 { get; set; }
        public virtual Product Product2 { get; set; }
    }
}
